create table patient_carer ( carer varchar(100), patient varchar(100));
insert into patient_carer (carer,patient) values ('carer01', 'patient01');
insert into patient_carer (carer,patient) values ('carer01', 'patient02');
insert into patient_carer (carer,patient) values ('carer01', 'patient03');
insert into patient_carer (carer,patient) values ('carer01', 'patient04');
insert into patient_carer (carer,patient) values ('carer01', 'patient05');
insert into patient_carer (carer,patient) values ('carer02', 'patient02');
insert into patient_carer (carer,patient) values ('carer02', 'patient04');
insert into patient_carer (carer,patient) values ('carer02', 'patient06');
insert into patient_carer (carer,patient) values ('carer03', 'patient06');
insert into patient_carer (carer,patient) values ('carer03', 'patient09');

create table relation(source_id character varchar(100),  target_id character varchar(100),  relation_id character varchar(100));
insert into relation(source_id, target_id, relation_id) values ('patient01@carbon.super','questionnaire_id_01','owner');
insert into relation(source_id, target_id, relation_id) values ('patient01@carbon.super','questionnaire_id_03','owner');
insert into relation(source_id, target_id, relation_id) values ('patient01@carbon.super','questionnaire_id_05','owner');
insert into relation(source_id, target_id, relation_id) values ('patient02@carbon.super','questionnaire_id_02','owner');
insert into relation(source_id, target_id, relation_id) values ('patient02@carbon.super','questionnaire_id_04','owner');
insert into relation(source_id, target_id, relation_id) values ('patient02@carbon.super','questionnaire_id_06','owner');

CREATE TABLE user_role(user_name character varchar(100), role_name character varchar(100));
insert into user_role(user_name, role_name) values ('clinitian01@carbon.super','clinitian');
insert into user_role(user_name, role_name) values ('clinitian02@carbon.super','clinitian');
insert into user_role(user_name, role_name) values ('clinitian03@carbon.super','clinitian');
insert into user_role(user_name, role_name) values ('therapist01@carbon.super','therapist');
insert into user_role(user_name, role_name) values ('therapist02@carbon.super','therapist');
insert into user_role(user_name, role_name) values ('therapist03@carbon.super','therapist');
insert into user_role(user_name, role_name) values ('patient01@carbon.super','patient');
insert into user_role(user_name, role_name) values ('patient02@carbon.super','patient');
insert into user_role(user_name, role_name) values ('patient03@carbon.super','patient');